// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(DoctorsOfficeContext))]
    [Migration("20260223164003_DbUpdatePatient")]
    partial class DbUpdatePatient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Domain.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultationTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationTypeId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ConsultationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsultationTypes", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("ConsultationType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cpr")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CounselingSession", b =>
                {
                    b.HasBaseType("Domain.Entities.ConsultationType");

                    b.HasDiscriminator().HasValue("Counseling");

                    b.HasData(
                        new
                        {
                            Id = new Guid("185a3999-762c-4d98-a601-5492b16d3e04"),
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            Name = "Counseling"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PerscriptionRenewal", b =>
                {
                    b.HasBaseType("Domain.Entities.ConsultationType");

                    b.HasDiscriminator().HasValue("PerscriptionRenewal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce3e1283-08af-4cc4-8b2f-e29b63a7de12"),
                            Duration = new TimeSpan(0, 0, 10, 0, 0),
                            Name = "Perscription Renewal"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RegularConsultation", b =>
                {
                    b.HasBaseType("Domain.Entities.ConsultationType");

                    b.HasDiscriminator().HasValue("Regular");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4adf9313-e990-4bfc-b186-a886179da195"),
                            Duration = new TimeSpan(0, 0, 20, 0, 0),
                            Name = "Regular"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vaccination", b =>
                {
                    b.HasBaseType("Domain.Entities.ConsultationType");

                    b.HasDiscriminator().HasValue("Vaccination");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e6f6390-2a8d-4144-9f3a-01eca22f5fea"),
                            Duration = new TimeSpan(0, 0, 10, 0, 0),
                            Name = "Vaccination"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Consultation", b =>
                {
                    b.HasOne("Domain.Entities.ConsultationType", "ConsultationType")
                        .WithMany()
                        .HasForeignKey("ConsultationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultationType");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
